title: Aminullah Prince
Email: aminullahprince@gmail.com
Mobile: +1 (747)724-3592
logo: /assets/img/head_shot.png
#description: Email: aminullahprince@gmail.com
Mobile: +1 (747)724-3592
show_downloads: false
theme: jekyll-theme-minimal
